/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "inverse-surface": "#2d3133",
        "on-primary-fixed-variant": "#005236",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#00367a",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "tertiary-container": "#71a1ff",
        "on-tertiary-fixed-variant": "#004395",
        "on-surface-variant": "#3c4a42",
        "on-secondary-fixed": "#131b2e",
        "error": "#ba1a1a",
        "primary-container": "#10b981",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "background": "#f7f9fb",
        "surface-tint": "#006c49",
        "surface-dim": "#d8dadc",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#001a42",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#4edea3",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed-dim": "#adc6ff",
        "outline-variant": "#bbcabf",
        "on-primary-container": "#00422b",
        "secondary-fixed-dim": "#bec6e0",
        "secondary": "#565e74",
        "surface-container-highest": "#e0e3e5",
        "primary": "#006c49",
        "on-primary": "#ffffff",
        "inverse-primary": "#4edea3",
        "outline": "#6c7a71",
        "on-surface": "#191c1e",
        "primary-fixed": "#6ffbbe",
        "secondary-container": "#dae2fd",
        "tertiary": "#005ac2",
        "surface": "#f7f9fb",
        "tertiary-fixed": "#d8e2ff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary-fixed": "#002113",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "xl": "48px",
        "sm": "8px",
        "unit": "4px",
        "xs": "4px",
        "gutter": "16px",
        "md": "16px",
        "margin": "24px"
      },
      fontFamily: {
        "h3": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "h3": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "h2": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "h1": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
